apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: config-cluster-flux
spec:
  releaseName: flux
  chart:
    spec:
      chart: flux
      version: "2.1.1" # {"$imagepolicy": "config-cluster-flux:flux:tag"}
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flux
        namespace: config-cluster-flux
  install:
    createNamespace: true
  interval: 5m0s
  targetNamespace: flux-system

