apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gotk-components.yaml

patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=20
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-dependency=5s
    target:
      kind: Deployment
      name: "(kustomize-controller|helm-controller|source-controller)"
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: AZURE_CLIENT_ID
          value: "d9cb0e6f-c3c2-41f1-ab80-f0b9686bf127"
    target:
      kind: Deployment
      name: "(helm-controller|source-controller|image-reflector-controller)"