apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "(source-controller|image-reflector-controller)"
      spec:
        provider: azure
    target:
      kind: Deployment
      name: "(source-controller|image-reflector-controller)"