apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: repository-istio
  namespace: flux-config
spec:
  interval: 24h
  url: https://istio-release.storage.googleapis.com/charts