apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: release-ingress-nginx
  namespace: flux-config
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: repository-ingress-nginx
  interval: 5m0s
  releaseName: ingress-nginx
  targetNamespace: kube-system
  values:
    defaultBackend:
      nodeSelector:
        kubernetes.io/os: "linux"
    controller:
      nginxplus: false
      ingressClassResource:
        name: nginx-oss
      ingressClass: nginx-oss
      allowSnippetAnnotations: true
      service:
        enabled: true
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-pls-create: "true"
          service.beta.kubernetes.io/azure-pls-name: "aks-loadbalancer-pls"
        internal:
          enabled: true
          type: LoadBalancer
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: In
                values:
                  - 'system'
      nodeSelector:
        kubernetes.io/os: "linux"
      config:
        entries:
          http2: "True"
        annotations-risk-level: Critical
      podDisruptionBudget:
        enabled: true
        annotations: {}
      enableSnippets: true
