apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-calico-api-server
  namespace: flux-config
spec:
  chart:
    spec:
      chart: adp-calico-helm-chart
      version: "0.0.4-prerelease24"
      sourceRef:
        kind: HelmRepository
        name: repository-adp-calico-helm-chart
  install:
    createNamespace: true
  interval: 5m0s
  releaseName: calico-api-server
  targetNamespace: calico-apiserver
  values:
    apiServer:
      enabled: true