apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-calico-network-policies
  namespace: flux-config
spec:
  chart:
    spec:
      chart: adp-calico-helm-chart
      version: "0.0.4-prerelease14"
      sourceRef:
        kind: HelmRepository
        name: repository-adp-calico-helm-chart
        namespace: flux-config
  install:
    createNamespace: true
  interval: 5m0s
  releaseName: calico-network-policies
  targetNamespace: calico-apiserver
  dependsOn:
  - name: release-calico-api-server