apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-adp-helm-core-calico-network-policies
  namespace: flux-config
spec:
  chart:
    spec:
      chart: adp-calico-helm
      version: "0.0.6"
      sourceRef:
        kind: HelmRepository
        name: repository-adp-helm-core-calico
        namespace: flux-config
  install:
    createNamespace: true
  interval: 5m0s
  releaseName: adp-helm-core-calico-network-policies
  targetNamespace: aatestns
  dependsOn:
  - name: release-adp-helm-core-calico