apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: release-calico-network-policies
  namespace: flux-config
spec:
  chart:
    spec:
      chart: adp-calico-helm-chart
      version: "0.1.4"
      sourceRef:
        kind: HelmRepository
        name: repository-adp-calico-helm-chart
  interval: 5m0s
  releaseName: calico-network-policies
  dependsOn:
  - name: release-calico-api-server
  - name: release-nginx-ingress
  - name: release-cert-manager
  values:
    aksIlbSubnetRange: "${LOAD_BALANCER_SUBNET_ADDRESS_PREFIX}"