apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-azure-service-operator
  namespace: flux-config-cluster
spec:
  chart:
    spec:
      chart: azure-service-operator
      version: "2.3.0"
      sourceRef:
        kind: HelmRepository
        name: repository-azure-service-operator
        namespace: flux-config-cluster
  install:
    createNamespace: true
  interval: 5m0s
  releaseName: azure-service-operator
  targetNamespace: azureserviceoperator-system
  dependsOn:
    - name: release-cert-manager
  values:
    azureSubscriptionID: ''
    azureTenantID: ''
    azureClientID: ''
    crdPattern: 'resources.azure.com/*;managedidentity.azure.com/*;authorization.azure.com/*;servicebus.azure.com/*;dbforpostgresql.azure.com/*'