apiVersion: v1
kind: Namespace
metadata:
  name: ffc-demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp-demo
  labels:
    app: aspnetapp-demo
  namespace: ffc-demo
  annotations:
    configmap.reloader.stakater.com/reload: "configmap-created-by-appconfig-provider"
    secret.reloader.stakater.com/reload: "secret-created-by-appconfig-provider-app1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetapp-demo
  template:
    metadata:
      labels:
        app: aspnetapp-demo
        azure.workload.identity/use: "true"
    spec:
      containers:
      - name: aspnetapp
        image: ssvadpinfcr3401.azurecr.io/mywebapp:v3
        ports:
        - containerPort: 80
        # env:
        # - name: Settings__Message
        #   value: "Message from the local configuration"
        # - name: Settings__FontColor
        #   value: "Black"
        envFrom:
        - configMapRef:
            name: configmap-created-by-appconfig-provider

---

apiVersion: v1
kind: Service
metadata:
  name: aspnetapp-demo-service
  namespace: ffc-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aspnetapp-demo

---

apiVersion: azconfig.io/v1beta1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
  namespace: ffc-demo
spec:
  endpoint: https://sndadpinfac1401.azconfig.io
  target:
    configMapName: configmap-created-by-appconfig-provider
  auth:
    workloadIdentity:
      managedIdentityClientId: aa3e6a68-11e0-45c5-931d-276c001bebe7   #TempCluster1 e0bd0434-d6f3-45c4-82ef-d2273453d064   #Workload Id
  keyValues:
    selectors:
      - keyFilter: '*'
        labelFilter: App1
    refresh:
      interval: 1m
      monitoring:
        keyValues:
          - key: Sentinel
            label: App1
