apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: services-repository
  namespace: config-cluster-flux
spec:
  interval: 5m
  ref:
    branch: users/kb/deploy-to-snd3-flux-changes
  url: ssh://git@github.com/DEFRA/adp-flux-services/
  secretRef:
    name: adp-flux-services-secret