apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: services-repository
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: features/kb/flux-changes
  url: https://github.com/DEFRA/adp-flux-services/