apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-cert-manager
  namespace: config-cluster-flux
spec:
  chart:
    spec:
      chart: cert-manager
      version: "v1.13.0"
      sourceRef:
        kind: HelmRepository
        name: repository-cert-manager
        namespace: config-cluster-flux
  install:
    createNamespace: true
  interval: 10m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true