apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-nginx-ingress
  namespace: config-cluster-flux
spec:
  chart:
    spec:
      chart: nginx-ingress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: repository-nginx-ingress
  install:
    createNamespace: true
  interval: 5m0s
  releaseName: nginx-ingress-plus
  targetNamespace: nginx-ingress
  values:
    defaultBackend:
      nodeSelector:
        kubernetes.io/os: "linux"
    controller:
      nginxplus: true
      service:
        create: true
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-pls-create: "true"
          service.beta.kubernetes.io/azure-pls-name: "aks-loadbalancer-pls"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "SNDADPNETNS1401"
      nodeSelector:
        kubernetes.io/os: "linux"