apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: repository-nginx-ingress
  namespace: config-cluster-flux
spec:
  interval: 5m0s
  url: https://helm.nginx.com/stable