apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: flux-system
  interval: 5m
  timeout: 3m
  prune: true
  path: ./services/environments/snd/01
  serviceAccountName: kustomize-controller
  postBuild:
    substitute:
      ENVIRONMENT: ""
      ACR_NAME: ""
      NAMESPACE: ""