apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: config-services-flux
spec:
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: config-services-flux
  interval: 5m
  timeout: 3m
  prune: true
  path: ./services/environments/snd/01
 