apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
  namespace: flux-config-cluster
spec:
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: flux-config-cluster
  interval: 5m
  timeout: 3m
  prune: true
  path: ./services/environments/snd/01
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: platform-vars
