apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: repository-app-config-service
  namespace: flux-config
spec:
  type: "oci"
  interval: 24h
  url: oci://mcr.microsoft.com/azure-app-configuration/helmchart