apiVersion: azconfig.io/v1beta1
kind: AzureAppConfigurationProvider
metadata:
  name: platform-vars
  namespace: config-cluster-flux
spec:
  endpoint: https://sndadpinfac1401.azconfig.io
  target:
    configMapName: platform-vars
  keyValues:
    selectors:
      - keyFilter: '*'
        labelFilter: Platform
    keyVaults:
      target:
        secretName: platform-secrets
      refresh:
        interval: 1m
    refresh:
      interval: 1m
      monitoring:
        keyValues:
          - key: Sentinel
            label: Platform