apiVersion: azconfig.io/v1beta1
kind: AzureAppConfigurationProvider
metadata:
  name: platform-vars
  namespace: config-cluster-flux
spec:
  endpoint: https://${APPCONFIG_NAME}.azconfig.io
  target:
    configMapName: platform-vars
  auth:
    workloadIdentity:
      managedIdentityClientId: ${APPCONFIG_MI_CLIENTID}
  keyValues:
    selectors:
      - keyFilter: '*'
        labelFilter: Platform
    keyVaults:
      target:
        secretName: platform-secrets
      auth:
        workloadIdentity:
          managedIdentityClientId: ${APPCONFIG_MI_CLIENTID}
      refresh:
        interval: 1m
    refresh:
      interval: 1m
      monitoring:
        keyValues:
          - key: Sentinel
            label: Platform