apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-app-config-service
  namespace: config-cluster-flux
spec:
  chart:
    spec:
      chart: stakater/reloader
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: repository-reloader
  install:
    createNamespace: true
  interval: 5m0s
  releaseName: app-config-reloader
  targetNamespace: reloader