apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-testkube
  namespace: flux-config
spec:
  interval: 5m0s
  targetNamespace: testkube
  releaseName: testkube
  chart:
    spec:
      chart: testkube
      sourceRef:
        kind: HelmRepository
        name: repository-testkube
        namespace: flux-config
      version: "1.15.25"
  values:
    testkube-api:
      uiIngress:
        enabled: true
        className: "nginx"
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header l5d-dst-override testkube-api.testkube.svc.cluster.local:8088;
            grpc_set_header l5d-dst-override testkube-api.testkube.svc.cluster.local:8088;

        path: /results
        hosts:
          - testkube-api.${ENVIRONMENT}3.adp.defra.gov.uk

    testkube-dashboard:
      enabled: "true"
      ingress:
        className: "nginx"
        enabled: "true" 
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header l5d-dst-override testkube-dashboard.testkube.svc.cluster.local:8080;
            grpc_set_header l5d-dst-override testkube-dashboard.testkube.svc.cluster.local:8080;          
        path: /
        hosts:
          - dashboard.snd3.adp.defra.gov.uk
      apiServerEndpoint: "testkube-api.${ENVIRONMENT}3.adp.defra.gov.uk/results"
